name: npm-publish
on:
  push:
    branches:
      - main
    paths:
      - 'easy-peasy-logger/dist/**'

jobs:
  gpr-publish:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
          scope: ${{ github.actor }}

      - name: Check if easy-peasy-logger has been updated
        id: epl
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: easy-peasy-logger/dist/package.json
          token: ${{ secrets.GT_TOKEN }}

      - name: Publish EPL to GitHub Package Registry
        if: steps.epl.outputs.changed == 'true'
        run: npm publish easy-peasy-logger/dist
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.EPL_TOKEN }}

  npm-publish:
    name: Publish to Node Package Manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org

      - name: Check if easy-peasy-logger has been updated
        id: epl
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: easy-peasy-logger/dist/package.json
          token: ${{ secrets.GT_TOKEN }}

      - name: Publishing to NPM
        if: steps.epl.outputs.changed == 'true'
        run: npm publish easy-peasy-logger/dist --access public --@costlydeveloper:registry=https://registry.npmjs.org/
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
